defaults: &defaults
  docker:
    - image: circleci/ruby:2.4-node
  working_directory: ~/repo

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-gem-cache-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          - v1-gem-cache-{{ arch }}-{{ .Branch }}-
          - v1-gem-cache-{{ arch }}-
      - run: bundle install
      - save_cache:
          paths:
            - ~/repo/.bundle
            - ~/.bundle
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run: bundle exec middleman build
  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run: bundle check || bundle install
      - run: bundle exec htmlproof ./build --only-4xx --check-favicon --check-html
  deploy:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run: bundle check || bundle install
      - run: bundle exec middleman build
      - run: ./deploy_prod.sh
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: source
