version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby
    steps:
      - checkout
      - run: bundle install
      - run: bundle exec middleman build
  test:
    docker:
      - image: circleci/ruby
    steps:
      - checkout
      - run: bundle exec htmlproof ./build --only-4xx --check-favicon --check-html
  deploy:
    docker:
      - image: circleci/ruby
    steps:
      - checkout
      - run: ./deploy_prod.sh
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: source
